import type { AcademySettings } from './schemas/academy-settings.schema';
import type { Course } from './schemas/course.schema';

/* ============================================================
 * Static design-preview data for the Courses / Academy screens.
 *
 * No backend, no mocks, no network — abode-be-v2 has no courses model yet,
 * and this is a display/design pass, not an integration. Screens read this
 * array directly. Edits made in the UI live only in that screen's component
 * state; they don't write back here, so a refresh resets everything.
 * ============================================================ */

export const DUMMY_COURSES: Course[] = [
  {
    id: '66cc0a0000000000000001',
    title: 'Selling Woodgate Prime',
    slug: 'selling-woodgate-prime',
    summary:
      "What Woodgate Prime costs, how the plan works, what the title is today, and when a client's plot gets allocated.",
    audience: 'realtor',
    estate_id: '665faaaa00000000000000a1',
    estate_name: 'Woodgate Prime',
    cover_url: null,
    status: 'published',
    published_at: '2026-08-14T00:00:00.000Z',
    require_in_order: false,
    grants_credential: false,
    credential_validity_months: null,
    credential_renewal: null,
    is_first_sale_path: true,
    modules_count: 4,
    learners_count: 128,
    completed_count: 78,
    estimated_minutes: 35,
  },
  {
    id: '66cc0a0000000000000002',
    title: 'Abode Associate Certification',
    slug: 'abode-associate-certification',
    summary: 'The five-module course every associate takes to earn the Abode certification badge.',
    audience: 'realtor',
    estate_id: null,
    estate_name: null,
    cover_url: null,
    status: 'published',
    published_at: '2026-07-01T00:00:00.000Z',
    require_in_order: false,
    grants_credential: true,
    credential_validity_months: 12,
    credential_renewal: 'refresher',
    is_first_sale_path: false,
    modules_count: 5,
    learners_count: 96,
    completed_count: 34,
    estimated_minutes: 48,
  },
  {
    id: '66cc0a0000000000000003',
    title: 'Selling The District',
    slug: 'selling-the-district',
    summary: 'The District: pricing, the plan, and what to tell a buyer about title today.',
    audience: 'realtor',
    estate_id: '665faaaa00000000000000a3',
    estate_name: 'The District',
    cover_url: null,
    status: 'published',
    published_at: '2026-08-22T00:00:00.000Z',
    require_in_order: false,
    grants_credential: false,
    credential_validity_months: null,
    credential_renewal: null,
    is_first_sale_path: false,
    modules_count: 4,
    learners_count: 41,
    completed_count: 9,
    estimated_minutes: 32,
  },
  {
    id: '66cc0a0000000000000004',
    title: 'Handling title questions',
    slug: 'handling-title-questions',
    summary: 'How to answer the title and C of O questions that come up most in a sales conversation.',
    audience: 'realtor',
    estate_id: null,
    estate_name: null,
    cover_url: null,
    status: 'published',
    published_at: '2026-08-08T00:00:00.000Z',
    require_in_order: false,
    grants_credential: false,
    credential_validity_months: null,
    credential_renewal: null,
    is_first_sale_path: false,
    modules_count: 3,
    learners_count: 64,
    completed_count: 31,
    estimated_minutes: 28,
  },
  {
    id: '66cc0a0000000000000005',
    title: 'Selling Empire Park',
    slug: 'selling-empire-park',
    summary: 'Empire Park: what is already built, the plan, and the allocation threshold.',
    audience: 'realtor',
    estate_id: '665faaaa00000000000000a6',
    estate_name: 'Empire Park',
    cover_url: null,
    status: 'draft',
    published_at: null,
    require_in_order: false,
    grants_credential: false,
    credential_validity_months: null,
    credential_renewal: null,
    is_first_sale_path: false,
    modules_count: 4,
    learners_count: 0,
    completed_count: 0,
    estimated_minutes: 30,
  },
  {
    id: '66cc0a0000000000000006',
    title: 'Understanding your land documents',
    slug: 'understanding-your-land-documents',
    summary: 'What a deed of assignment, survey and C of O each are, and what a buyer should expect to receive.',
    audience: 'buyer',
    estate_id: null,
    estate_name: null,
    cover_url: null,
    status: 'draft',
    published_at: null,
    require_in_order: false,
    grants_credential: false,
    credential_validity_months: null,
    credential_renewal: null,
    is_first_sale_path: false,
    modules_count: 3,
    learners_count: 0,
    completed_count: 0,
    estimated_minutes: 22,
  },
  {
    id: '66cc0a0000000000000007',
    title: 'What allocation means',
    slug: 'what-allocation-means',
    summary: "Allocation explained for buyers: what it is, and when a client's plot gets assigned.",
    audience: 'buyer',
    estate_id: null,
    estate_name: null,
    cover_url: null,
    status: 'draft',
    published_at: null,
    require_in_order: false,
    grants_credential: false,
    credential_validity_months: null,
    credential_renewal: null,
    is_first_sale_path: false,
    modules_count: 2,
    learners_count: 0,
    completed_count: 0,
    estimated_minutes: 15,
  },
];

export const DUMMY_ACADEMY_SETTINGS: AcademySettings = {
  first_sale_path_course_id: '66cc0a0000000000000001',
  first_sale_path_course_title: 'Selling Woodgate Prime',
};
