/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetAllAdminAssets($page: Int!, $limit: Int!) {\n    getAllAdminAssets(page: $page, limit: $limit) {\n      count\n      data {\n        _id\n        asset_location\n        asset_name\n        asset_price\n        asset_size\n        asset_type\n        asset_unit\n        asset_pictures\n        sold\n        description\n        title\n        newAsset\n        asset_option {\n          size\n          unit\n          price\n          zero_months\n          three_months\n          six_months\n          five_months\n          seven_months\n          one_month\n          one_month_initial_payment\n          twelve_months\n          initial_payment\n          five_months_initial_payment\n          seven_months_initial_payment\n          development_fee\n          monthly_installment\n          flex_payment_plans {\n            description\n            duration_months\n            initial_payment\n            monthly_installment\n            price\n            unit\n          }\n        }\n      }\n    }\n  }\n": typeof types.GetAllAdminAssetsDocument,
    "\n  query Statistics {\n    getAssetInventoryData {\n      statistics {\n        totalAssets\n        totalWorth\n        totalFlexAssets\n        totalFlexWorth\n        totalFullOwnershipAssets\n        totalFullOwnershipWorth\n      }\n    }\n  }\n": typeof types.StatisticsDocument,
    "\n  mutation CreateFlexAsset($createFlexAssetInput: CreateFlexAssetInput!) {\n    createFlexAsset(createFlexAssetInput: $createFlexAssetInput) {\n      _id\n      asset_name\n    }\n  }\n": typeof types.CreateFlexAssetDocument,
    "\n  query ViewAssetByName($assetName: String!, $assetType: String) {\n    viewAssetByName(assetName: $assetName, assetType: $assetType) {\n      available_unit\n      unit_sold\n      expected_return\n      total_value\n      sizes\n    }\n  }\n": typeof types.ViewAssetByNameDocument,
    "\n  query ViewAssetOptionDataByName($assetName: String!, $assetType: String!) {\n    viewAssetOptionDataByName(assetName: $assetName, assetType: $assetType) {\n      sizes {\n        size\n        available_unit\n        value\n        unit_sold\n        expected_return\n      }\n    }\n  }\n": typeof types.ViewAssetOptionDataByNameDocument,
    "\n  mutation CreateFullOwnershipAsset($createFullOwnershipAssetInput: CreateFullOwnershipAssetInput!) {\n    createFullOwnershipAsset(createFullOwnershipAssetInput: $createFullOwnershipAssetInput) {\n      _id\n      asset_name\n    }\n  }\n": typeof types.CreateFullOwnershipAssetDocument,
    "\n  query ViewSubscribedCustomersOnAsset($assetName: String!, $assetType: String, $filter: String, $size: Int, $startDate: String, $endDate: String, $subscriberType: String) {\n    viewSubscribedCustomersOnAsset(assetName: $assetName, assetType: $assetType, filter: $filter, size: $size, startDate: $startDate, endDate: $endDate, subscriberType: $subscriberType) {\n      totalSubscribers\n      userDetails {\n        _id\n        name\n        email\n        phone_number\n        salesPerson\n        assetName\n        sizeBought\n        unitPurchased\n        landPrice\n        landAmountPaid\n        documentPrice\n        documentAmountPaid\n        month_subscription\n        startDate\n        nextPaymentDate\n        isDefaulted\n        isSuspended\n      }\n      unitSold\n      earningReceived\n      expectedEarning\n      defaultedUsers\n      suspendedUsers\n      completedPayments\n      totalPlotsSold\n    }\n  }\n": typeof types.ViewSubscribedCustomersOnAssetDocument,
    "\n  query GetAdminDashboardDetails($startDate: String, $endDate: String) {\n    getAdminDashboardDetails(startDate: $startDate, endDate: $endDate) {\n      associate_pro_users\n      associate_users\n      default_users\n      suspended_users\n      monthly_recurring_revenue\n      sales\n      top_associates {\n        userName\n        email\n        gender\n        amount_commissions\n        amount_brought\n        firstName\n        lastName\n        no_of_referral\n      }\n      top_selling_prop {\n        asset_name\n        asset_pictures\n        asset_location\n        units_subscribed\n        amount_broughtin\n      }\n      total_payable\n      users\n      total_asset\n      inflow\n      outflow\n      total_wallet_balance\n      suspended_payment_plans\n    }\n  }\n": typeof types.GetAdminDashboardDetailsDocument,
};
const documents: Documents = {
    "\n  query GetAllAdminAssets($page: Int!, $limit: Int!) {\n    getAllAdminAssets(page: $page, limit: $limit) {\n      count\n      data {\n        _id\n        asset_location\n        asset_name\n        asset_price\n        asset_size\n        asset_type\n        asset_unit\n        asset_pictures\n        sold\n        description\n        title\n        newAsset\n        asset_option {\n          size\n          unit\n          price\n          zero_months\n          three_months\n          six_months\n          five_months\n          seven_months\n          one_month\n          one_month_initial_payment\n          twelve_months\n          initial_payment\n          five_months_initial_payment\n          seven_months_initial_payment\n          development_fee\n          monthly_installment\n          flex_payment_plans {\n            description\n            duration_months\n            initial_payment\n            monthly_installment\n            price\n            unit\n          }\n        }\n      }\n    }\n  }\n": types.GetAllAdminAssetsDocument,
    "\n  query Statistics {\n    getAssetInventoryData {\n      statistics {\n        totalAssets\n        totalWorth\n        totalFlexAssets\n        totalFlexWorth\n        totalFullOwnershipAssets\n        totalFullOwnershipWorth\n      }\n    }\n  }\n": types.StatisticsDocument,
    "\n  mutation CreateFlexAsset($createFlexAssetInput: CreateFlexAssetInput!) {\n    createFlexAsset(createFlexAssetInput: $createFlexAssetInput) {\n      _id\n      asset_name\n    }\n  }\n": types.CreateFlexAssetDocument,
    "\n  query ViewAssetByName($assetName: String!, $assetType: String) {\n    viewAssetByName(assetName: $assetName, assetType: $assetType) {\n      available_unit\n      unit_sold\n      expected_return\n      total_value\n      sizes\n    }\n  }\n": types.ViewAssetByNameDocument,
    "\n  query ViewAssetOptionDataByName($assetName: String!, $assetType: String!) {\n    viewAssetOptionDataByName(assetName: $assetName, assetType: $assetType) {\n      sizes {\n        size\n        available_unit\n        value\n        unit_sold\n        expected_return\n      }\n    }\n  }\n": types.ViewAssetOptionDataByNameDocument,
    "\n  mutation CreateFullOwnershipAsset($createFullOwnershipAssetInput: CreateFullOwnershipAssetInput!) {\n    createFullOwnershipAsset(createFullOwnershipAssetInput: $createFullOwnershipAssetInput) {\n      _id\n      asset_name\n    }\n  }\n": types.CreateFullOwnershipAssetDocument,
    "\n  query ViewSubscribedCustomersOnAsset($assetName: String!, $assetType: String, $filter: String, $size: Int, $startDate: String, $endDate: String, $subscriberType: String) {\n    viewSubscribedCustomersOnAsset(assetName: $assetName, assetType: $assetType, filter: $filter, size: $size, startDate: $startDate, endDate: $endDate, subscriberType: $subscriberType) {\n      totalSubscribers\n      userDetails {\n        _id\n        name\n        email\n        phone_number\n        salesPerson\n        assetName\n        sizeBought\n        unitPurchased\n        landPrice\n        landAmountPaid\n        documentPrice\n        documentAmountPaid\n        month_subscription\n        startDate\n        nextPaymentDate\n        isDefaulted\n        isSuspended\n      }\n      unitSold\n      earningReceived\n      expectedEarning\n      defaultedUsers\n      suspendedUsers\n      completedPayments\n      totalPlotsSold\n    }\n  }\n": types.ViewSubscribedCustomersOnAssetDocument,
    "\n  query GetAdminDashboardDetails($startDate: String, $endDate: String) {\n    getAdminDashboardDetails(startDate: $startDate, endDate: $endDate) {\n      associate_pro_users\n      associate_users\n      default_users\n      suspended_users\n      monthly_recurring_revenue\n      sales\n      top_associates {\n        userName\n        email\n        gender\n        amount_commissions\n        amount_brought\n        firstName\n        lastName\n        no_of_referral\n      }\n      top_selling_prop {\n        asset_name\n        asset_pictures\n        asset_location\n        units_subscribed\n        amount_broughtin\n      }\n      total_payable\n      users\n      total_asset\n      inflow\n      outflow\n      total_wallet_balance\n      suspended_payment_plans\n    }\n  }\n": types.GetAdminDashboardDetailsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAllAdminAssets($page: Int!, $limit: Int!) {\n    getAllAdminAssets(page: $page, limit: $limit) {\n      count\n      data {\n        _id\n        asset_location\n        asset_name\n        asset_price\n        asset_size\n        asset_type\n        asset_unit\n        asset_pictures\n        sold\n        description\n        title\n        newAsset\n        asset_option {\n          size\n          unit\n          price\n          zero_months\n          three_months\n          six_months\n          five_months\n          seven_months\n          one_month\n          one_month_initial_payment\n          twelve_months\n          initial_payment\n          five_months_initial_payment\n          seven_months_initial_payment\n          development_fee\n          monthly_installment\n          flex_payment_plans {\n            description\n            duration_months\n            initial_payment\n            monthly_installment\n            price\n            unit\n          }\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAllAdminAssets($page: Int!, $limit: Int!) {\n    getAllAdminAssets(page: $page, limit: $limit) {\n      count\n      data {\n        _id\n        asset_location\n        asset_name\n        asset_price\n        asset_size\n        asset_type\n        asset_unit\n        asset_pictures\n        sold\n        description\n        title\n        newAsset\n        asset_option {\n          size\n          unit\n          price\n          zero_months\n          three_months\n          six_months\n          five_months\n          seven_months\n          one_month\n          one_month_initial_payment\n          twelve_months\n          initial_payment\n          five_months_initial_payment\n          seven_months_initial_payment\n          development_fee\n          monthly_installment\n          flex_payment_plans {\n            description\n            duration_months\n            initial_payment\n            monthly_installment\n            price\n            unit\n          }\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Statistics {\n    getAssetInventoryData {\n      statistics {\n        totalAssets\n        totalWorth\n        totalFlexAssets\n        totalFlexWorth\n        totalFullOwnershipAssets\n        totalFullOwnershipWorth\n      }\n    }\n  }\n"): (typeof documents)["\n  query Statistics {\n    getAssetInventoryData {\n      statistics {\n        totalAssets\n        totalWorth\n        totalFlexAssets\n        totalFlexWorth\n        totalFullOwnershipAssets\n        totalFullOwnershipWorth\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateFlexAsset($createFlexAssetInput: CreateFlexAssetInput!) {\n    createFlexAsset(createFlexAssetInput: $createFlexAssetInput) {\n      _id\n      asset_name\n    }\n  }\n"): (typeof documents)["\n  mutation CreateFlexAsset($createFlexAssetInput: CreateFlexAssetInput!) {\n    createFlexAsset(createFlexAssetInput: $createFlexAssetInput) {\n      _id\n      asset_name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ViewAssetByName($assetName: String!, $assetType: String) {\n    viewAssetByName(assetName: $assetName, assetType: $assetType) {\n      available_unit\n      unit_sold\n      expected_return\n      total_value\n      sizes\n    }\n  }\n"): (typeof documents)["\n  query ViewAssetByName($assetName: String!, $assetType: String) {\n    viewAssetByName(assetName: $assetName, assetType: $assetType) {\n      available_unit\n      unit_sold\n      expected_return\n      total_value\n      sizes\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ViewAssetOptionDataByName($assetName: String!, $assetType: String!) {\n    viewAssetOptionDataByName(assetName: $assetName, assetType: $assetType) {\n      sizes {\n        size\n        available_unit\n        value\n        unit_sold\n        expected_return\n      }\n    }\n  }\n"): (typeof documents)["\n  query ViewAssetOptionDataByName($assetName: String!, $assetType: String!) {\n    viewAssetOptionDataByName(assetName: $assetName, assetType: $assetType) {\n      sizes {\n        size\n        available_unit\n        value\n        unit_sold\n        expected_return\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreateFullOwnershipAsset($createFullOwnershipAssetInput: CreateFullOwnershipAssetInput!) {\n    createFullOwnershipAsset(createFullOwnershipAssetInput: $createFullOwnershipAssetInput) {\n      _id\n      asset_name\n    }\n  }\n"): (typeof documents)["\n  mutation CreateFullOwnershipAsset($createFullOwnershipAssetInput: CreateFullOwnershipAssetInput!) {\n    createFullOwnershipAsset(createFullOwnershipAssetInput: $createFullOwnershipAssetInput) {\n      _id\n      asset_name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ViewSubscribedCustomersOnAsset($assetName: String!, $assetType: String, $filter: String, $size: Int, $startDate: String, $endDate: String, $subscriberType: String) {\n    viewSubscribedCustomersOnAsset(assetName: $assetName, assetType: $assetType, filter: $filter, size: $size, startDate: $startDate, endDate: $endDate, subscriberType: $subscriberType) {\n      totalSubscribers\n      userDetails {\n        _id\n        name\n        email\n        phone_number\n        salesPerson\n        assetName\n        sizeBought\n        unitPurchased\n        landPrice\n        landAmountPaid\n        documentPrice\n        documentAmountPaid\n        month_subscription\n        startDate\n        nextPaymentDate\n        isDefaulted\n        isSuspended\n      }\n      unitSold\n      earningReceived\n      expectedEarning\n      defaultedUsers\n      suspendedUsers\n      completedPayments\n      totalPlotsSold\n    }\n  }\n"): (typeof documents)["\n  query ViewSubscribedCustomersOnAsset($assetName: String!, $assetType: String, $filter: String, $size: Int, $startDate: String, $endDate: String, $subscriberType: String) {\n    viewSubscribedCustomersOnAsset(assetName: $assetName, assetType: $assetType, filter: $filter, size: $size, startDate: $startDate, endDate: $endDate, subscriberType: $subscriberType) {\n      totalSubscribers\n      userDetails {\n        _id\n        name\n        email\n        phone_number\n        salesPerson\n        assetName\n        sizeBought\n        unitPurchased\n        landPrice\n        landAmountPaid\n        documentPrice\n        documentAmountPaid\n        month_subscription\n        startDate\n        nextPaymentDate\n        isDefaulted\n        isSuspended\n      }\n      unitSold\n      earningReceived\n      expectedEarning\n      defaultedUsers\n      suspendedUsers\n      completedPayments\n      totalPlotsSold\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAdminDashboardDetails($startDate: String, $endDate: String) {\n    getAdminDashboardDetails(startDate: $startDate, endDate: $endDate) {\n      associate_pro_users\n      associate_users\n      default_users\n      suspended_users\n      monthly_recurring_revenue\n      sales\n      top_associates {\n        userName\n        email\n        gender\n        amount_commissions\n        amount_brought\n        firstName\n        lastName\n        no_of_referral\n      }\n      top_selling_prop {\n        asset_name\n        asset_pictures\n        asset_location\n        units_subscribed\n        amount_broughtin\n      }\n      total_payable\n      users\n      total_asset\n      inflow\n      outflow\n      total_wallet_balance\n      suspended_payment_plans\n    }\n  }\n"): (typeof documents)["\n  query GetAdminDashboardDetails($startDate: String, $endDate: String) {\n    getAdminDashboardDetails(startDate: $startDate, endDate: $endDate) {\n      associate_pro_users\n      associate_users\n      default_users\n      suspended_users\n      monthly_recurring_revenue\n      sales\n      top_associates {\n        userName\n        email\n        gender\n        amount_commissions\n        amount_brought\n        firstName\n        lastName\n        no_of_referral\n      }\n      top_selling_prop {\n        asset_name\n        asset_pictures\n        asset_location\n        units_subscribed\n        amount_broughtin\n      }\n      total_payable\n      users\n      total_asset\n      inflow\n      outflow\n      total_wallet_balance\n      suspended_payment_plans\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;